### ISSUE TITLE
Input data appears to have issues

### ISSUE THREAD

**Issue by ssddanbrown** [peep24/array-tree-builder-task#1]
:wave: Started to check the scenario against the function logic but came across issues with the input data.

I've added my full process of checking and the issues found, within the readme [of my fork](https://github.com/ssddanbrown/array-tree-builder-task). I did not re-run the functions here, I used only the output provided in this repo, although I had renamed the files to organise things a tad, and added in the functions and original input from stackoverflow as reference. 

To summarise what I found in regards to the input data:
- There are about 2.2k dupe ids.
- There are 26 items that have a parent referencing a non-existing item.

Let me know if these conditions are expected, since I did not expect them hence they were not accounted for in my original function.
Also, your output seemed to contain >12k items, which is 5k more items than the input. If you are expecting the possibility of more output items than input items, let me know as that was also against my expectations when writing the function.

**Comment by peep24** [comment]
Thank you so much for your extremely well put together response. 

You helped me to see a very critical misunderstanding I had made in regard to the data i was receiving. I think the data is now correct. I checked with your Id dupe function and only found one id which was repeated three times.

In order to move forward with your solution, I needed to alter this to use a composite key. I still strongly suspect there is data missing. 

I wrote a function to test this in a very crude fashion by string searching. Not ideal, but seems to suggest out of 5508 potentially 1280 are missing.

Any thoughts you could give me would be really helpful. 

Thanks Dan 👍

**Comment by ssddanbrown** [comment]
Happy to help!

> I wrote a function to test this in a very crude fashion by string searching. Not ideal, but seems to suggest out of 5508 potentially 1280 are missing.

You can do a quick check by text-searching `"id":` within the data:

- fixed_data.json - 5508 matches
- output.json - 917 matches

So about 4591 short. You can also quickly get an indication from the filesizes, should expect the ouput to be larger than the input data (If formatted the same) due to the extra whitespace and `children` properties.

[I adjusted my](https://github.com/ssddanbrown/array-tree-builder-task/commit/8874f97b5aa897e071857cc46874dcd5c81fd07e) `check_*.php` functions to check the new `fixed_data.json` input file with its combined key.
Now no duplicate ids within input data but 3044 items reference parents that do not exist. I'd assume this is a large cause of the current missing items. 

---

As en extra note, that parent key would make me a little uneasy but it ultimately depends on context. 
If the `type` property is open to user edit, or could ever be or start with a number, it will mess up the `parent` property. 
Personal, I'd add a seperation character within this, which could never be part the `type` or `id` (so `Action:4366` for example) or I'd split the `parent` property to `parent_type` and `parent_id`

**Comment by peep24** [comment]
I have reformatted the data so it now uses an associative array to hold both the id and the type for the id property and parent. 

This is how the source data is presented anyway so I should not have been trying to create a composite key. 

I have rewritten the functions for checking dupes and checking for no parents. 

I rewrote the new function to make use of the new data schema.

If I do a search of “id”: in the source data I get 16523, but in the output I have 14663.

Still something is amiss. 

Any thoughts?

**Comment by ssddanbrown** [comment]
With your changes to the `buildTree` function it was no longer taking the type+id composite key into account hence it was de-duplicating ids across types in its operation.
I've [tweaked the function in this commit](https://github.com/ssddanbrown/array-tree-builder-task/commit/2a5250c96f371752d66f4630dc73df8772a136d3#diff-f3af43469893b15281f66b0fb173905f673a1f2d75a4a9f1b55f058bf7175278) to use the new composite key format.

> If I do a search of “id”

Probably safer to use `"name:"` now due to the duplication per-item for `"id": `. I done a quick check after the changes above and it seems to match, have not deeply checked the output though. 

> I have rewritten the functions for checking dupes and checking for no parents.

Yeah, I noticed this although reverted the logic in my commit back to their original format.
Be a little cautious about reducing lines of code while introducing computational complexity, such as by replacing simple loop operations with array functions.

Taking the `check_duplicate_ids.php` as an example, This would normally loop through the array twice, so with the new input length of `5508` this is `11,016` iterations. The rewritten version with `array_filter` calls that function for each item on each array loop, so `5508*5508=30,338,064` times, with function calls also being more costly than a loop. The original has linear scaling, the latter has exponential scaling.

**Comment by peep24** [comment]
Oh my god its beautiful, Thank you so much for your help! i think we are there now. 

Agreed on the array_filter. I noticed this was noticably slower and assumed was something like that. But as a Jn Dev i reach for the easy tools!
